SUBDIRS = cdvdfsv cdvdman clearspu dmacman eeconf eesync excepman fileio heaplib igreeting intrman ioman loadcore loadfile mcman mcserv modload osdsnd padman reboot romdrv secrman sifcmd sifinit sifman sio2man ssbusc stdio sysclib sysmem threadman timeman udnl vblank

include $(PS2SDK)/samples/Makefile
